version: "3"

services:

  web:
    build:
      context: ./docker/web
    volumes:
      - ./shinylaravel:/my/web/app:ro
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4455:80
    environment:
      CLIENT_MAX_BODY_SIZE: 100M
      GLOBAL_MAX_BODY_SIZE: 100M
    working_dir: /my/web/app
    

  php:
    build:
      context: ./docker/php
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./shinylaravel:/my/web/app
    working_dir: /my/web/app

  # node:
  #   container_name: nodejs
  #   image: node:lts
  #   working_dir: /var/www/html/app/
  #   entrypoint: /bin/bash
  #   ports:
  #     - 4567:4567
  #   volumes:
  #     - ./shinybooks/:/var/www/html/app
  #   tty: true
  #   user: ${PUID}:${PGID}
  
  db:
    image: mysql:8.0.23
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data: